### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by iyuzuri** [hasenj/mangareader#1]
Hi,
I downloaded your works and run `build.py` using Python 3.7 _(which I believe that's what I'm supposed to do, because I can't found the _how to_ in README)_

then I got this error when running it:
```
Traceback (most recent call last):
  File "D:\mangareader-master\build.py", line 38, in <module>
    do_exe()                     # call py2exe
  File "D:\mangareader-master\build.py", line 27, in do_exe
    ('art', ['art/icon.png']),
  File "C:\Python\Python37-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python\Python37-32\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Python\Python37-32\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Python\Python37-32\lib\site-packages\py2exe\distutils_buildexe.py", line 188, in run
    self._run()
  File "C:\Python\Python37-32\lib\site-packages\py2exe\distutils_buildexe.py", line 267, in _run
    builder.analyze()
  File "C:\Python\Python37-32\lib\site-packages\py2exe\runtime.py", line 158, in analyze
    self.mf.import_package(modname[:-2])
  File "C:\Python\Python37-32\lib\site-packages\py2exe\mf3.py", line 92, in import_package
    self.import_hook(name)
  File "C:\Python\Python37-32\lib\site-packages\py2exe\mf3.py", line 120, in import_hook
    module = self._gcd_import(name)
  File "C:\Python\Python37-32\lib\site-packages\py2exe\mf3.py", line 274, in _gcd_import
    return self._find_and_load(name)
  File "C:\Python\Python37-32\lib\site-packages\py2exe\mf3.py", line 357, in _find_and_load
    self._scan_code(module.__code__, module)
  File "C:\Python\Python37-32\lib\site-packages\py2exe\mf3.py", line 388, in _scan_code
    for what, args in self._scan_opcodes(code):
  File "C:\Python\Python37-32\lib\site-packages\py2exe\mf3.py", line 417, in _scan_opcodes
    yield "store", (names[oparg],)
IndexError: tuple index out of range
```
Also perhaps include compiled .exe for major system like Windows and Linux?

Thank you

**Comment by hasenj** [comment]
Hi, thank you for checking this out.

The last commit here was in 2010, and I was working on some version of python 2.x, and I don't even remember if it was on Linux or Windows.

Anyway, the main file is not `build.py`, it's `mangareader/qt_gui.py`.

Note that there's a hardcoded variable `test_path` that should be changed to a path where you have a folder (with potentially other folders inside it) that has the images.
